# Generated by Django 3.2.9 on 2022-09-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
